name: Build and Publish Tauri CLI

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use for release'     
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  # build-amd64:
  #   name: Build and Publish Tauri CLI for ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       include:
  #         - os: ubuntu-18.04
  #           artifact_name: cargo-tauri
  #           asset_name: tauri-cli_linux
  #         - os: windows-latest
  #           artifact_name: cargo-tauri.exe
  #           asset_name: tauri-cli_windows.exe
  #         - os: macos-latest
  #           artifact_name: cargo-tauri
  #           asset_name: tauri-cli_macos
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #       with:
  #         repository: 'tauri-apps/tauri'
  #     - name: Build
  #       run: cd tooling/cli.rs && cargo build --release
  #     - name: Upload binaries to release
  #       uses: svenstaro/upload-release-action@v2
  #       with:
  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
  #         file: ./tooling/cli.rs/target/release/${{ matrix.artifact_name }}
  #         tag: tauri-cli-${{ github.event.inputs.version }}
  #         asset_name: ${{ matrix.asset_name }}
  #         release_name: Tauri CLI ${{ github.event.inputs.version }}
  build-other-archs:
    name: Build and Publish Tauri CLI for ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact_name: cargo-tauri
            asset_name: tauri-cli_linux-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'tauri-apps/tauri'
      - name: Build
        run: docker buildx build --platform linux/arm64 -t tauri-app --output out .
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./out/tooling/cli.rs/target/release/${{ matrix.artifact_name }}
          tag: tauri-cli-${{ github.event.inputs.version }}
          asset_name: ${{ matrix.asset_name }}
          release_name: Tauri CLI ${{ github.event.inputs.version }}
